import com.sun.net.httpserver.*;import java.io.*;import java.util.*;import model.*;
public final class InvestigationFindingApiHandler implements HttpHandler{
 private final InvestigationFindingDao dao; private final CaseDao cases; private final SessionManager sessions; private final AuditLogDao audit=new AuditLogDao();
 public InvestigationFindingApiHandler(InvestigationFindingDao d,CaseDao c,SessionManager s){dao=d;cases=c;sessions=s;}
 public void handle(HttpExchange e)throws IOException{try{String caseId=param(e.getRequestURI().getRawQuery(),"caseId");if(caseId==null||caseId.isBlank()){HttpUtil.text(e,400,"{\"error\":\"caseId is required\"}","application/json");return;}if(cases.findAll().stream().noneMatch(x->x.getCaseId().equals(caseId))){HttpUtil.text(e,404,"{\"error\":\"Case not found\"}","application/json");return;}String m=e.getRequestMethod();
  if("GET".equals(m)){StringBuilder j=new StringBuilder("{\"findings\":[");for(InvestigationFinding f:dao.findByCaseId(caseId)){if(j.charAt(j.length()-1)!= '[')j.append(',');j.append(json(f));}j.append("],\"evidence\":[");for(String[] v:dao.evidenceForCase(caseId)){if(j.charAt(j.length()-1)!='[')j.append(',');j.append("{\"id\":\"").append(q(v[0])).append("\",\"description\":\"").append(q(v[1])).append("\",\"collectionDate\":\"").append(q(v[2])).append("\",\"custodian\":\"").append(q(v[3])).append("\",\"custodyLogs\":").append(v[4]).append('}');}j.append("]}");HttpUtil.text(e,200,j.toString(),"application/json");return;}
  Map<String,String> f=HttpUtil.form(e);UserSession u=session(e);String by=u==null?null:u.getUserId();
  if("POST".equals(m)){String action=f.getOrDefault("action","finding");if("link".equals(action)){long fid=Long.parseLong(f.getOrDefault("findingId","0"));String eid=f.get("evidenceId");String rel=valid(f.get("relationship"),new String[]{"SUPPORTS","CONTRADICTS","CONTEXT"},null);if(fid<=0||eid==null||rel==null){HttpUtil.text(e,400,"{\"error\":\"findingId, evidenceId and relationship are required\"}","application/json");return;}dao.link(fid,eid,rel,f.get("notes"));audit.record(by,"FINDING_EVIDENCE_LINKED","FINDING",String.valueOf(fid),"CASE_ID="+caseId+"; evidence="+eid+"; relationship="+rel);HttpUtil.text(e,201,"{\"ok\":true}","application/json");return;}
   String title=f.get("title"),desc=f.get("description"),type=valid(f.get("type"),new String[]{"FACT","OBSERVATION","LEAD","HYPOTHESIS","INFERENCE"},"OBSERVATION");if(title==null||title.isBlank()||desc==null||desc.isBlank()){HttpUtil.text(e,400,"{\"error\":\"title and description are required\"}","application/json");return;}long id=dao.create(caseId,title,desc,type,by);audit.record(by,"FINDING_CREATED","FINDING",String.valueOf(id),"CASE_ID="+caseId+"; type="+type+"; title="+title);HttpUtil.text(e,201,"{\"id\":"+id+"}","application/json");return;}
  if("PATCH".equals(m)){long id=Long.parseLong(f.getOrDefault("id","0"));String st=valid(f.get("status"),new String[]{"OPEN","UNDER_REVIEW","SUPPORTED","CONTRADICTED","RESOLVED"},null);if(id<=0||st==null){HttpUtil.text(e,400,"{\"error\":\"valid id and status are required\"}","application/json");return;}dao.updateStatus(id,st);audit.record(by,"FINDING_STATUS_CHANGED","FINDING",String.valueOf(id),"CASE_ID="+caseId+"; status="+st);HttpUtil.text(e,200,"{\"id\":"+id+",\"status\":\""+q(st)+"\"}","application/json");return;}
  HttpUtil.text(e,405,"{\"error\":\"Method not allowed\"}","application/json");
 }catch(Exception ex){ex.printStackTrace();HttpUtil.text(e,500,"{\"error\":\"Unable to process investigation findings\"}","application/json");}}
 private UserSession session(HttpExchange e){String t=HttpUtil.cookie(e,"CCECS_SESSION");return t==null?null:sessions.get(t).orElse(null);}
 private static String valid(String v,String[] a,String d){if(v==null||v.isBlank())return d;for(String x:a)if(x.equals(v))return v;return d;}private static String param(String raw,String name){if(raw==null)return null;for(String pair:raw.split("&")){String[]p=pair.split("=",2);if(p.length==2&&p[0].equals(name))return java.net.URLDecoder.decode(p[1],java.nio.charset.StandardCharsets.UTF_8);}return null;}private static String q(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r");}
 private String json(InvestigationFinding f)throws Exception{StringBuilder j=new StringBuilder("{\"id\":"+f.getId()+",\"caseId\":\""+q(f.getCaseId())+"\",\"title\":\""+q(f.getTitle())+"\",\"description\":\""+q(f.getDescription())+"\",\"type\":\""+q(f.getType())+"\",\"status\":\""+q(f.getStatus())+"\",\"evidence\":[");for(FindingEvidence x:dao.evidenceForFinding(f.getId())){if(j.charAt(j.length()-1)!='[')j.append(',');j.append("{\"evidenceId\":\"").append(q(x.getEvidenceId())).append("\",\"description\":\"").append(q(x.getEvidenceDescription())).append("\",\"relationship\":\"").append(q(x.getRelationship())).append("\",\"notes\":\"").append(q(x.getNotes())).append("\",\"custodian\":\"").append(q(x.getCustodian())).append("\"}");}return j.append("]}").toString();}
}
