import java.sql.*;import java.util.*;import model.*;
public final class InvestigationFindingDao {
 public List<InvestigationFinding> findByCaseId(String caseId)throws SQLException{List<InvestigationFinding> out=new ArrayList<>();String q="SELECT f.id,f.case_id,f.title,f.description,f.type,f.status,COALESCE(f.created_by,''),f.created_at FROM investigation_findings f WHERE f.case_id=? ORDER BY f.id";try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement(q)){p.setString(1,caseId);try(ResultSet r=p.executeQuery()){while(r.next())out.add(new InvestigationFinding(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8)));}}return out;}
 public List<FindingEvidence> evidenceForFinding(long findingId)throws SQLException{List<FindingEvidence> out=new ArrayList<>();String q="SELECT fe.id,fe.finding_id,fe.evidence_id,e.description,fe.relationship,COALESCE(fe.notes,''),COALESCE(e.current_custodian,'') FROM finding_evidence fe JOIN evidence e ON e.id=fe.evidence_id WHERE fe.finding_id=? ORDER BY fe.id";try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement(q)){p.setLong(1,findingId);try(ResultSet r=p.executeQuery()){while(r.next())out.add(new FindingEvidence(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7)));}}return out;}
 public List<String[]> evidenceForCase(String caseId)throws SQLException{List<String[]> out=new ArrayList<>();String q="SELECT e.id,e.description,e.collection_date,e.current_custodian,(SELECT COUNT(*) FROM evidence_logs l WHERE l.evidence_id=e.id) FROM evidence e WHERE e.case_id=? ORDER BY e.collection_date DESC";try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement(q)){p.setString(1,caseId);try(ResultSet r=p.executeQuery()){while(r.next())out.add(new String[]{r.getString(1),r.getString(2),r.getString(3),r.getString(4),String.valueOf(r.getInt(5))});}}return out;}
 public long create(String caseId,String title,String desc,String type,String createdBy)throws SQLException{String q="INSERT INTO investigation_findings(case_id,title,description,type,status,created_by) VALUES(?,?,?,?, 'OPEN',?)";try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){p.setString(1,caseId);p.setString(2,title);p.setString(3,desc);p.setString(4,type);p.setString(5,createdBy);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){return r.next()?r.getLong(1):0;}}}
 public void updateStatus(long id,String status)throws SQLException{try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("UPDATE investigation_findings SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?")){p.setString(1,status);p.setLong(2,id);if(p.executeUpdate()!=1)throw new SQLException("Finding not found");}}
 public void link(long findingId,String evidenceId,String relationship,String notes)throws SQLException{String q="INSERT OR IGNORE INTO finding_evidence(finding_id,evidence_id,relationship,notes) VALUES(?,?,?,?)";try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement(q)){p.setLong(1,findingId);p.setString(2,evidenceId);p.setString(3,relationship);p.setString(4,notes);p.executeUpdate();}}
}
