import com.sun.net.httpserver.*;import java.io.IOException;import java.sql.*;import java.util.*;import model.*;
public final class InvestigationTaskApiHandler implements HttpHandler{
 private final InvestigationTaskDao tasks; private final CaseDao cases; private final SessionManager sessions; private final AuditLogDao audit=new AuditLogDao();
 public InvestigationTaskApiHandler(InvestigationTaskDao t,CaseDao c,SessionManager s){tasks=t;cases=c;sessions=s;}
 public void handle(HttpExchange e)throws IOException{try{String method=e.getRequestMethod();String caseId=param(e.getRequestURI().getRawQuery(),"caseId");if(caseId==null||caseId.isBlank()){HttpUtil.text(e,400,"{\"error\":\"caseId is required\"}","application/json");return;}if(cases.findAll().stream().noneMatch(x->x.getCaseId().equals(caseId))){HttpUtil.text(e,404,"{\"error\":\"Case not found\"}","application/json");return;}
  if("GET".equals(method)){StringBuilder j=new StringBuilder("[");for(InvestigationTask x:tasks.findByCaseId(caseId)){if(j.length()>1)j.append(',');j.append(json(x));}HttpUtil.text(e,200,j.append(']').toString(),"application/json");return;}
  Map<String,String> f=HttpUtil.form(e);UserSession u=session(e);if("POST".equals(method)){String title=f.get("title");if(title==null||title.isBlank()){HttpUtil.text(e,400,"{\"error\":\"title is required\"}","application/json");return;}String priority=valid(f.get("priority"),new String[]{"LOW","MEDIUM","HIGH","CRITICAL"},"MEDIUM");String assigned=blankToNull(f.get("assignedTo"));String due=blankToNull(f.get("dueDate"));long id=tasks.create(caseId,title,f.get("description"),assigned,priority,due,u==null?null:u.getUserId());audit.record(u==null?null:u.getUserId(),"TASK_CREATED","TASK",String.valueOf(id),"CASE_ID="+caseId+"; title="+title+"; priority="+priority);HttpUtil.text(e,201,"{\"id\":"+id+",\"status\":\"PENDING\"}","application/json");return;}
  if("PATCH".equals(method)){long id=Long.parseLong(f.getOrDefault("id","0"));String status=valid(f.get("status"),new String[]{"PENDING","IN_PROGRESS","BLOCKED","COMPLETED","CANCELLED"},null);if(id<=0||status==null){HttpUtil.text(e,400,"{\"error\":\"valid id and status are required\"}","application/json");return;}tasks.updateStatus(id,status);audit.record(u==null?null:u.getUserId(),"TASK_STATUS_CHANGED","TASK",String.valueOf(id),"CASE_ID="+caseId+"; status="+status);HttpUtil.text(e,200,"{\"id\":"+id+",\"status\":\""+q(status)+"\"}","application/json");return;}
  HttpUtil.text(e,405,"{\"error\":\"Method not allowed\"}","application/json");
 }catch(Exception ex){ex.printStackTrace();HttpUtil.text(e,500,"{\"error\":\"Unable to process investigation tasks\"}","application/json");}}
 private UserSession session(HttpExchange e){String t=HttpUtil.cookie(e,"CCECS_SESSION");return t==null?null:sessions.get(t).orElse(null);}
 private static String valid(String v,String[] a,String d){if(v==null||v.isBlank())return d;for(String x:a)if(x.equals(v))return v;return d;}
 private static String blankToNull(String s){return s==null||s.isBlank()?null:s;}
 private static String param(String raw,String name){if(raw==null)return null;for(String pair:raw.split("&")){String[]p=pair.split("=",2);if(p.length==2&&p[0].equals(name))return java.net.URLDecoder.decode(p[1],java.nio.charset.StandardCharsets.UTF_8);}return null;}
 private static String q(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r");}
 private static String json(InvestigationTask x){return "{\"id\":"+x.getId()+",\"caseId\":\""+q(x.getCaseId())+"\",\"title\":\""+q(x.getTitle())+"\",\"description\":\""+q(x.getDescription())+"\",\"assignedTo\":\""+q(x.getAssignedTo())+"\",\"assignedOfficerName\":\""+q(x.getAssignedOfficerName())+"\",\"priority\":\""+q(x.getPriority())+"\",\"status\":\""+q(x.getStatus())+"\",\"dueDate\":\""+q(x.getDueDate())+"\",\"completedAt\":\""+q(x.getCompletedAt())+"\"}";}
}
